[package]
name = "tictactui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
rand = "0.8.5"
rand_derive2 = "0.1"
termion = "2.0.1"
tui = "0.19.0"
